NAME_DISPLAY_MAP: dict = {
    "BasicSpreadStrategy": "基础价差策略",
    "StatisticalArbitrageStrategy": "统计套利策略",
    "strategy_name": "策略名称",
    "spread_name": "价差名称",
    "vt_symbol": "本地代码",
    "direction": "方向",
    "price": "价格",
    "volume": "委托数量",
    "interval": "每轮间隔（秒）",
    "offset": "开平",
    "payup": "加价跳数",
    "max_pos": "最大持仓数量",
    "short_price": "卖出平仓价差",
    "cover_price": "买入平仓价差",
    "sell_price": "卖出开仓价差",
    "buy_price": "买入开仓价差",
    "boll_window": "布林窗口期数",
    "boll_dev": "布林带倍数",
}
